### ISSUE TITLE
DataTemplate Trigger

### ISSUE THREAD

**Issue by jaspervanzfive** [rodrigoelp/wpfgesturerecognizer#15]
Hi how can i put the interaction.trigger into DataTemplate.Triggers?
IS that possible?

**Comment by rodrigoelp** [comment]
Hi @jaspervanzfive, the gesture recognizer is part of the interactivity namespace as opposed to the presentation framework. These sorts of objects get applied directly to the object as opposed to the style.

You can (however) applied a similar behaviour to the one explained on this [stackoverflow answer](https://stackoverflow.com/questions/22321966/interaction-triggers-in-style-in-resourcedictionary-wpf)

**Comment by jaspervanzfive** [comment]
Dude thanks for replying , Now i have questions regarding how can i run a
certain method from my codes behind.

What i wanted to is when I swipe right , I wanted to run my METHOD named
DisplayText() .
Can i achieve that?

my code:

  <i:Interaction.Triggers>

<r:GestureRecognizer TriggerOnGesture="SwipeDown">
                        <ei:CallMethodAction MethodName="DisplayText"/>
                    </r:GestureRecognizer>

                </i:Interaction.Triggers>


Hope you can help me to achieve what i wanted to.

**Comment by rodrigoelp** [comment]
Hi @jaspervanzfive,

You need to test the target object of your `CallMethodAction` otherwise it won't know which object you are trying to invoke the action on.

One trick to get this is to name the user control, window or page of the object you have the code behind in.

For instance:

```xml
<UserControl x:Name="this">
    <Grid>
        <r:GestureRecognizer TriggerOnGesture="SwipeDown">
           <ei:CallMethodAction TargetObject={Binding ElementName=this} MethodName="DisplayTest" />
        </r:GestureRecognizer>
    </Grid>
</UserControl>
```

Please, take the code above with a pinch of salt as I just typed it without checking it (I don't have currently vs on my mac)

Hope this helps :)
